# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_mrid', models.CharField(max_length=100)),
                ('order_refid', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=100)),
                ('marketplace', models.CharField(max_length=100)),
            ],
        ),
    ]
